### ISSUE TITLE
Configure network and filesystem

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/cargo-task-wasm#2]
We should add a config to inherit the network and filesystem. Filesystem is probably easiest, using something like dockers volume mapping:

```toml
[package.metadata.tasks]
my-task = { dirs = [["/lib/foo", "/foo"]] }  # Map the dir `/lib/foo` to `/foo`
```

Networking is probably a little more involved - I'm not sure there is a way to restrict specific address name lookups in Wasmtime (we should check). But we probably need a way to both enable blanket network inheritance as well as a way to whitelist specific domains / IPs:

```toml
[package.metadata.tasks]
my-task = { net = true }                               # Blanket access to the entire network
my-task = { net = ["tcp/127.0.0.1", "tcp/0.0.0.0"] }   # Allow specific addresses
my-task = { net = ["example.com"] }                    # Allow specific domains
```

We should probably figure out how this is going to be supported in `cargo-component` too, because we need a way to support this in the sandbox as well.
