### ISSUE TITLE
Support pulling from OCI

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/cargo-task-wasm#3]
This should probably also be able to point at OCI registries and pull Wasm Components from that. Something like this should work I think?:

```toml
[package.metadata.tasks]
my-cool-task = "gchr.io/username/package-name:version"
```

This would probably conflict with the assumed semver string though. So maybe we need to split this up into separate fields? Again: we should probably figure out what the plan is for `cargo-component` and mirror that if we go down this route.
